import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getSupabaseServiceRole } from "@/lib/supabase/server";

export async function POST(request: Request) {
  const authHeader = request.headers.get("authorization") ?? "";
  const token = authHeader.replace(/^Bearer\s+/i, "");
  if (!token) return NextResponse.json({ error: "Missing auth token" }, { status: 401 });

  const supabase = getSupabaseServiceRole();
  const { data: userData, error: userError } = await supabase.auth.getUser(token);
  if (userError || !userData.user) {
    return NextResponse.json({ error: "Invalid auth token" }, { status: 401 });
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("*")
    .eq("id", userData.user.id)
    .maybeSingle();
  if (!profile?.family_code) {
    return NextResponse.json({ error: "No family code found" }, { status: 400 });
  }

  const familyCode = profile.family_code as string;
  const { data: playerProfile } = await supabase
    .from("profiles")
    .select("id,name")
    .eq("family_code", familyCode)
    .eq("role", "player")
    .maybeSingle();
  const playerId = playerProfile?.id ?? userData.user.id;
  const month = new Date();
  month.setDate(1);
  const monthKey = month.toISOString().slice(0, 10);
  const monthStart = monthKey;
  const monthEnd = new Date(month.getFullYear(), month.getMonth() + 1, 0).toISOString().slice(0, 10);

  const [{ data: checkins }, { data: sessions }, { data: matches }, { data: badges }] =
    await Promise.all([
      supabase.from("daily_checkins").select("*").eq("family_code", familyCode).gte("checkin_date", monthStart).lte("checkin_date", monthEnd),
      supabase.from("workout_sessions").select("*").eq("user_id", playerId).gte("scheduled_date", monthStart).lte("scheduled_date", monthEnd),
      supabase.from("matches").select("*").eq("family_code", familyCode).gte("match_date", monthStart).lte("match_date", monthEnd),
      supabase.from("badges").select("*").eq("user_id", playerId).order("earned_at", { ascending: false }).limit(5),
    ]);

  const hours = (sessions ?? []).reduce((sum: number, row: any) => sum + Number(row.duration_minutes ?? 0) / 60, 0);
  const completed = (sessions ?? []).filter((row: any) => row.completed).length;
  const areas = [...new Set((checkins ?? []).flatMap((row: any) => row.focus_areas ?? []))].slice(0, 8);
  const title = `${playerProfile?.name ?? profile.name ?? "Player"} monthly report`;
  const summary = {
    hoursTrained: Math.round(hours * 10) / 10,
    sessionsCompleted: completed,
    checkins: checkins?.length ?? 0,
    matches: matches?.length ?? 0,
    focusAreas: areas,
    recentBadges: (badges ?? []).map((b: any) => b.title),
  };

  const pdfBytes = await buildPdf(title, [
    `Family code: ${familyCode}`,
    `Month: ${month.toLocaleDateString("en-US", { month: "long", year: "numeric" })}`,
    `Hours trained: ${summary.hoursTrained}`,
    `Sessions completed: ${summary.sessionsCompleted}`,
    `Daily check-ins: ${summary.checkins}`,
    `Matches logged: ${summary.matches}`,
    `Focus areas: ${areas.join(", ") || "None logged yet"}`,
    `Recent badges: ${summary.recentBadges.join(", ") || "None yet"}`,
    "Upcoming month preview: keep weekly training consistent, log match results, and update UTR after verified results.",
  ]);

  const storagePath = `${familyCode}/${monthKey}.pdf`;
  const upload = await supabase.storage.from("parent-reports").upload(storagePath, pdfBytes, {
    contentType: "application/pdf",
    upsert: true,
  });
  if (upload.error) return NextResponse.json({ error: upload.error.message }, { status: 500 });

  const signed = await supabase.storage.from("parent-reports").createSignedUrl(storagePath, 60 * 60 * 24 * 30);
  const publicUrl = signed.data?.signedUrl ?? "";

  const { data, error } = await supabase
    .from("parent_reports")
    .upsert(
      {
        family_code: familyCode,
        player_id: playerId,
        month: monthKey,
        title,
        summary,
        storage_path: storagePath,
        public_url: publicUrl,
      },
      { onConflict: "family_code,month" }
    )
    .select("*")
    .single();
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data);
}

async function buildPdf(title: string, lines: string[]) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  page.drawText("Seeded", { x: 48, y: 730, size: 18, font: bold, color: rgb(0.18, 0.29, 0.17) });
  page.drawText(title, { x: 48, y: 690, size: 24, font: bold, color: rgb(0.12, 0.12, 0.1) });
  let y = 640;
  lines.forEach((line) => {
    page.drawText(line.slice(0, 92), { x: 48, y, size: 12, font, color: rgb(0.24, 0.24, 0.2) });
    y -= 26;
  });
  page.drawText("Generated by Seeded.", { x: 48, y: 60, size: 10, font, color: rgb(0.42, 0.42, 0.37) });
  return pdf.save();
}
